from .dr_science import *
from .elon import *
from .elon2 import *
from .cpp_coding import *
from .react_template import *
from .rewoo_template import *
from .openai_template import *
from .vanilla_template import *
from .openai_memory_template import *
from .vanilla-ziyu import *
from .scholar-ziyu import *
from .test_agent import *
from .agent1 import *
from .agent4 import *
from .pdfagent3 import *
